calender/urls.py
####################################################################################################################
# Created by Daniel Ratnaras ITRS Group Ltd
####################################################################################################################

from django.conf.urls import url
from calender import views, token
from django.contrib import admin
from django.contrib.auth import views as auth_views
urlpatterns = [
    # The home view ('/calender/')
    url(r'^$', views.home, name='home'),
    # Redirect to get token ('/calender/gettoken/')
    url(r'^gettoken/$', views.gettoken, name='gettoken'),
    # url(r'^maps/$', views.maps, name='maps'),
    # dashboard view ('/caldender/dashboard')
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # dashboard_appointment view (calender/dashboard/appointment)
    url(r'^dashboard/appointments/$', views.dashboard_appointments, name='dashboardAppointments'),
    # route planner view
    url(r'^dashboard/routeplanner/$', views.dashboard_routePlanner, name='routePlanner'),
    # get booking url
    url(r'^dashboard/bookingurl/$', views.dashboard_bookingUrl, name='dashboardBookingUrl'),
    # change password
    url(r'^dashboard/change_password/$', views.change_password, name='change_password'),
    # generate booking URL
    url(r'^dashboard/generatebookingurl/(?P<name>[\w ]+)/(?P<email>[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)$', token.create_token, name='GenerateBookingUrl'),
    # booking by token
    url(r'^booking/(?P<token>[\w.:\-_=]+)$', views.clientBooking_for_token, name='clientBookingToken'),
    #Get avilable Times for appointment booking
    url(r'^getTimes/$', views.getTimes, name='getTimes'),
    # get times for user
    url(r'^getTimes/(?P<token>[\w.:\-_=]+)$', views.getTimes_for_user, name='getTimes_for_user'),
    # get events for dashboard view
    url(r'^getEventsDashboard/$', views.getEventsDashboard, name='getEventsDashboard'),
    # get events for today
    url(r'^getEventsForToday/$', views.get_events_for_today, name='getEventsForToday'),
    # url(r'^login/$', auth_views.login, name='login'),
    url(r'^login/$', auth_views.login, {'template_name':'calender/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),

]

python3_cal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from calender import views

urlpatterns = [
    # Invoke the home view in the tutorial app by default
    url(r'^$', views.home, name='home'),
    # Defer any URLS to the /tutorial directory to the tutorial app
    url(r'^calendar/', include('calender.urls', namespace='calender')),
    url(r'^admin/', admin.site.urls),
]

calender/forms.py
####################################################################################################################
# Created by Daniel Ratnaras ITRS Group Ltd
####################################################################################################################

from django import forms
class ClientAppointmentForm (forms.Form):
    # name = forms.CharField(label = 'Name', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Name ...','name' : 'f1-first-name', 'class' : 'f1-first-name form-control', 'id' : 'f1-first-name'}))
    # email = forms.EmailField(label = 'Email', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Email ...','name' : 'f1-email', 'class' : 'f1-email form-control', 'id' : 'f1-email'}))
    date = forms.CharField(label = 'Date', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Date ...','name' : 'f1-Date', 'class' : 'f1-Date form-control', 'id' : 'f1-Date'}))
    time = forms.CharField(label = 'Time', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Time ...','name' : 'f1-time', 'class' : 'f1-time form-control', 'id' : 'f1-Time'}))
    address = forms.CharField(label = 'Address', widget=forms.Textarea(attrs={'placeholder': 'Address ...','name' : 'f1-about-yourself', 'class' : 'f1-about-yourself form-control', 'id' : 'f1-about-yourself'}))

    # forms.attrs.update({})
    # forms.attrs.update({'placeholder' : 'First name...'})
    # forms.attrs.update({'class' : 'f1-first-name form-control'})
    # forms.attrs.update({'id' : 'f1-first-name'})
    # q = forms.CharField(label='search',
    #                     )


    # <!--<input type="text" name="f1-first-name" placeholder="" class="f1-first-name form-control" id="f1-first-name">-->
class AppointmentFormAnalystDashboard(forms.Form):
    name = forms.CharField(label = 'Name', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Name ...','name' : 'f1-first-name', 'class' : 'f1-first-name form-control', 'id' : 'f1-first-name'}))
    email = forms.EmailField(label = 'Email', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Email ...','name' : 'f1-email', 'class' : 'f1-email form-control', 'id' : 'f1-email'}))
    date = forms.CharField(label = 'Date', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Date ...','name' : 'f1-Date', 'class' : 'f1-Date form-control', 'id' : 'f1-Date'}))
    time = forms.CharField(label = 'Time', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Time ...','name' : 'f1-time', 'class' : 'f1-time form-control', 'id' : 'f1-Time'}))
    address = forms.CharField(label = 'Address', widget=forms.Textarea(attrs={'placeholder': 'Address ...','name' : 'f1-about-yourself', 'class' : 'f1-about-yourself form-control', 'id' : 'f1-about-yourself'}))

class BookingUrlEmailForm(forms.Form):
    initial_subject= "ITRS Site Visit"

    client_name = forms.CharField(label = 'Name', max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'ng-model':'name' }))
    to_Recipients = forms.EmailField(label = 'Email', max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'type':'email'}))
    # carbon_copy = forms.EmailField(label = 'CC', max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    subject = forms.CharField(label = 'Subject', max_length=100, initial=initial_subject, widget=forms.TextInput(attrs={'class':'form-control'}))
    body = forms.CharField( widget=forms.Textarea(attrs={'class':'form-control'}))

class BookingLinkGeneratorForm(forms.Form):
    name = forms.CharField(label = 'Name', max_length=100)
    email = forms.CharField(label = 'Email', max_length=100)

class BookingUrlEmailForm1(forms.Form):
    initial_subject= "ITRS Site Visit"
    to_Recipients = forms.EmailField(label = 'To', max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    # carbon_copy = forms.EmailField(label = 'CC', max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))
    subject = forms.CharField(label = 'Subject', max_length=100, initial=initial_subject, widget=forms.TextInput(attrs={'class':'form-control'}))

class BookingUrlEmailForm2(forms.Form):
    body = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))

calender/views.py
####################################################################################################################
# Created by Daniel Ratnaras ITRS Group Ltd
####################################################################################################################

from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from calender.outlookservice import get_me
from calender.outlookservice import create_appointment
from calender.authhelper import get_signin_url, get_token_from_code,get_token_from_refresh_token
from calender.outlookservice import  get_events_by_range, get_my_events,send_email
from django.contrib.auth.decorators import login_required
from django.template import Context
from .forms import ClientAppointmentForm, AppointmentFormAnalystDashboard, BookingUrlEmailForm
from django.core.exceptions import ObjectDoesNotExist
from calender.token import *
import time
import json
import re
import dateutil.parser
import datetime
from datetime import timedelta
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect


from django.utils import six

@login_required
def home(request):
    # Check if user has connected app with their outlook, if not direct to connection page
    try:
        outh = OutlookAuth.objects.get(user_email=request.user.email)
        return dashboard(request)
    except ObjectDoesNotExist:
        redirect_uri = request.build_absolute_uri(reverse('calender:gettoken'))
        sign_in_url = get_signin_url(redirect_uri)
        c = Context({'sign_in_url': sign_in_url})
        # return render(request, 'calender/index.html' , c)
        return render(request, 'calender/dashboard_outlookSync.html' , c)
#


def gettoken(request):
    auth_code = request.GET['code']
    # print("auth_code" + auth_code)

    redirect_uri = request.build_absolute_uri(reverse('calender:gettoken'))
    token = get_token_from_code(auth_code, redirect_uri)
    access_token = token['access_token']
    user = get_me(access_token)
    refresh_token = token['refresh_token']
    expires_in = token['expires_in']

    ouath = OutlookAuth.objects.create(user_email = user['EmailAddress'], refresh_token = refresh_token, auth_code = auth_code, user = request.user)

    # expires_in is in seconds
    # Get current timestamp (seconds since Unix Epoch) and
    # add expires_in to get expiration time
    # Subtract 5 minutes to allow for clock differences
    expiration = int(time.time()) + expires_in - 300

    # Save the token in the session
    request.session['access_token'] = access_token
    request.session['refresh_token'] = refresh_token
    request.session['token_expires'] = expiration
    request.session['user_email'] = user['EmailAddress']


    return dashboard(request)
    # return HttpResponse('User Email: {0}, Access token: {1}'.format(user['EmailAddress'], access_token))

@login_required
def dashboard_appointments(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:

        form = AppointmentFormAnalystDashboard(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            date = form.cleaned_data['date']
            time = form.cleaned_data['time']
            address = form.cleaned_data['address']

            oauth = getUser(request)
            # oauth = OutlookAuth.objects.get(pk=1)
            auth_code = oauth.auth_code
            user_email = oauth.user_email
            rt = oauth.refresh_token
            redirect_uri = request.build_absolute_uri(reverse('calender:gettoken'))


            json = get_token_from_refresh_token(rt, redirect_uri)
            token = json["access_token"]



            # user_email = "dratnaras@itrsgroup.onmicrosoft.com"
            response = create_appointment(token, user_email, date, time, email, name, address)

            # send email to analyst
            # send_mail(
            #     'New Site Visit Booking',
            #     name + ' has booked a new appointment with you on ' + date +' at ' +time,
            #     'tempus@itrsgroup.onmicrosoft.com',
            #     ['dratnaras@itrsgroup.com'],
            #     fail_silently=False,
            #     )
            #
            c =  Context({'status_code' : response })
            messages.success(request, 'Appointment Created!')
            return redirect('calender:dashboardAppointments')
        else:
            messages.error(request, 'Unable to create appointment')



    # if a GET (or any other method) we'll create a blank form
    else:
        form = AppointmentFormAnalystDashboard()



    return render(request, 'calender/dashboard_appointments.html', {'form': form})

@login_required
def dashboard_bookingUrl(request):
    # s = SessionStore()
    # if request.session.get('booking_url_token', False):
    if request.session.get('booking_url_token', None) == None:
        request.session['booking_url_token'] = create_token_str_not_saved_in_db(request)

    body = "Hello {{name}},\n\n" \
          "{{user}} is available for a technical site visit.\n\n" \
          "If you would like to take us up on this offer please click on the link below and select a time that works best for you.\n\n" \
          "https://{{ host }}/calendar/booking/"+request.session.get('booking_url_token', None)+"\n\n" \
          "Regards,\n\n" \
          "{{user}} "
    form = BookingUrlEmailForm(initial={'body':body})

    # request.session['booking_url_token'] \
    # print("initial "+ request.session['booking_url_token'])
    # "https://{{ host }}/calender/booking/"+request.session['booking_url_token']+"\n\n" \

    # print("dosplay"+ booking_url_token)
    # +"https://{{ host }}/calender/booking/"+create_token_str(request)+"\n\n" + \





    # print("initial" + booking_url_token)
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:


        form = BookingUrlEmailForm(request.POST)
        # check whether it's valid:
        if form.is_valid():

            to_recipients = form.cleaned_data['to_Recipients']
            client_name = form.cleaned_data['client_name']
            subject = form.cleaned_data['subject']
            body = form.cleaned_data['body']

            oauth = getUser(request)
            # oauth = OutlookAuth.objects.get(pk=1)
            auth_code = oauth.auth_code
            user_email = oauth.user_email
            rt = oauth.refresh_token
            redirect_uri = request.build_absolute_uri(reverse('calender:gettoken'))
            json = get_token_from_refresh_token(rt, redirect_uri)
            token = json["access_token"]
            add_token_to_db(request.user, request.session['booking_url_token'], client_name, to_recipients)

            # print("save"  + booking_url_token)

            # user_email = "dratnaras@itrsgroup.onmicrosoft.com"
            response = send_email(token, user_email, to_recipients,body, subject)
            request.session['booking_url_token'] = None


            c =  Context({'status_code' : response,
                          'form': form})

            # return HttpResponse("<script>alert('message sent')</script>")
            messages.success(request, 'Email Sent!')
            return redirect('calender:dashboardBookingUrl')
        else:
            messages.error(request, 'Unable to send email')
            # return render(request, 'calender/dashboard_bookingUrl.html', c)
            # return HttpResponse(status=204)
    # if a GET (or any other method) we'll create a blank form
    else:
        # form = BookingUrlEmailForm(initial={'interest_rate': 3.5, 'number_of_years':5})
        # body = "Hello {{name}},\n\n" \
        #        "{{user}} is available for a technical site visit.\n\n" \
        #        "If you would like to take us up on this offer please click on the link below and select a time that works best for you.\n\n" \
        #        "https://{{ host }}/calender/booking/"+request.session.get('booking_url_token')+"\n\n"\
        #        "Regards,\n\n" \
        #        "{{user}} "
        # # print("dosplay"+ booking_url_token)
        #        # +"https://{{ host }}/calender/booking/"+create_token_str(request)+"\n\n" + \
        #
        # form = BookingUrlEmailForm(initial={'body':body})

        return render(request, 'calender/dashboard_bookingUrl.html', {'form': form})

@login_required
def dashboard(request):
    return render(request, 'calender/dashboard_home.html')


@login_required
def dashboard_routePlanner(request):
    # context = {'user':request.user}
    return render(request, 'calender/dashboard_routePlanner.html')


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('calender:change_password')
        else:
            messages.error(request, 'Please correct the error')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'calender/dashboard_change_password.html', {
        'form': form
    })



def clientBooking_for_token(request,token):
    if check_token_valid(token):
        name_token = get_clientName_from_token(token)
        email_token = get_clientEmail_from_token(token)

        # print(email)

        if (request.method == 'POST'):
            # create a form instance and populate it with data from the request:

calender/templates/calender/createEvents.html
<html>
    <head>
        <h1>
            event created
            {{status_code}}
        </h1>

    </head>

</html>

calender/templates/calender/dashboard_appointments.html
{% extends 'calender/dashboard_base.html' %}
{% load static %}

{% block content %}

<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Appointments</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>

    <div class="row">
        <!--Print error or success messages -->
        {% for message in messages %}
        <div class=" col-lg-12 alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Schedule Appointments
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body"/>
                <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <p></p>
                    <input type="submit" value="Submit" class ="btn btn-primary"/>
                </form>
            </div>
            <!-- /.panel-body -->

        </div>

    </div>
</div>
<!-- /.container-fluid -->
</div>


<script type="text/javascript">

    $(document).ready(function() {

        var dateToday = new Date();
        var $date = $('#f1-Date').pickadate({
            format: 'dd/mm/yyyy',
            altFormat: "yyyy-mm-dd",
            formatSubmit: 'yyyy-mm-dd',
            min: dateToday,
            disable: [1, 7],
            hiddenSuffix: ''


        });
        var datePicker = $date.pickadate('picker')

        var $time = $('#f1-Time');
//        $time.hide();
////    initialsise picker

//    var timeField = $('#f1-Time')
        var dateToday = new Date();
        var $time = $('#f1-Time').pickatime({
            min: [9, 00],
            max: [17, 00],
            formatSubmit: 'HH:i',
            hiddenSuffix: ''
        });

        var picker = $time.pickatime('picker')


        datePicker.on({


            open: function() {
                picker.clear()
                picker.set('enable', true)
//            $timePickerInput.clear()
            },

            close: function () {


                dateSelect = datePicker.get('select', 'yyyy-mm-dd')
                console.log(dateSelect)


                function timePicker(time) {

                    picker.set('disable', time)
                    $time.show()

                }

            }

        })


    });


</script>

{% endblock %}

calender/templates/calender/dashboard_base.html
    {% load static %}

    <!DOCTYPE html>
    <html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
        <meta charset="utf-8">

        <link rel="shortcut icon" href="https://www.itrsgroup.com/sites/default/files/favicon.ico" type="image/vnd.microsoft.icon" />

        <title>Tempus</title>

        <!--"{% static 'calender/bootstrap.min.css' %}"-->

        <!-- Bootstrap Core CSS -->
        <link href="{% static 'calender/dashboard-bootstrap/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- MetisMenu CSS -->
        <link href="{% static 'calender/dashboard-bootstrap/vendor/metisMenu/metisMenu.min.css'%}" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="{% static 'calender/dashboard-bootstrap/dist/css/sb-admin-2.css'%}" rel="stylesheet">

        <!-- Morris Charts CSS -->
        <link href="{% static 'calender/dashboard-bootstrap/vendor/morrisjs/morris.css'%}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{% static 'calender/dashboard-bootstrap/vendor/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">

        <link rel="stylesheet" href="{% static 'calender/dhtmlx/dhtmlxscheduler.css' %}" type="text/css" media="screen" title="no title"
              charset="utf-8">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <![endif]-->

        <!--jdatepicker css-->
        <link rel="stylesheet" href="{% static 'calender/date-picker/pickadate.js-3.5.6/lib/themes/default.css' %}">
        <link rel="stylesheet" href="{% static 'calender/date-picker/pickadate.js-3.5.6/lib/themes/default.date.css' %}">
        <link rel="stylesheet" href="{% static 'calender/date-picker/pickadate.js-3.5.6/lib/themes/default.time.css' %}">

        <!--progress bar-->
        <!--Progress bar-->
        <script src="{% static 'calender/nprogress/nprogress.js' %}"></script>
        <link rel='stylesheet' href="{% static 'calender/nprogress/nprogress.css' %}"/>


        <!--JDatePicker-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

        <script src="{% static 'calender/date-picker/pickadate.js-3.5.6/lib/picker.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'calender/date-picker/pickadate.js-3.5.6/lib/picker.date.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'calender/date-picker/pickadate.js-3.5.6/lib/picker.time.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'calender/date-picker/pickadate.js-3.5.6/lib/legacy.js' %}" type="text/javascript" charset="utf-8"></script>


        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <script src="{% static 'calender/dhtmlx/dhtmlxscheduler.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'calender/dhtmlx/ext/dhtmlxscheduler_recurring.js' %}" type="text/javascript" charset="utf-8"></script>
        <script src="{% static 'calender/dhtmlx/ext/dhtmlxscheduler_minical.js' %}" type="text/javascript" charset="utf-8"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js"></script>




    </head>

    <body  onload="init();">

    <div id="loading-bar-container"></div>
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'calender:dashboard' %}">ITRS <strong>TEMPUS</strong></a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">

                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i>{{ user.first_name }}</a>
                        <!--</li>-->
                        <!--<li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>-->
                        <!--</li>-->
                        <li class="divider"></li>
                            <li><a href="{% url 'calender:change_password' %}"><i class="fa fa-key fa-fw"></i> Change Password</a>
                            <li><a href="{% url 'calender:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!--/.navbar-top-links-->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <!--<li class="sidebar-search">-->
                            <!--<div class="input-group custom-search-form">-->
                                <!--<input type="text" class="form-control" placeholder="Search...">-->
                                <!--<span class="input-group-btn">-->
                                        <!--<button class="btn btn-default" type="button">-->
                                            <!--<i class="fa fa-search"></i>-->
                                        <!--</button>-->
                                    <!--</span>-->

                            <!--</div>-->

                            <!-- /input-group -->
                        <!--</li>-->

                        <li>
                            <a href="{% url 'calender:dashboard' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'calender:dashboardBookingUrl' %}"><i class="fa fa-key fa-fw"></i> Booking Link Generator</a>

                        </li>
                        <li>
                            <a href="{% url 'calender:routePlanner' %}"><i class="fa fa-wrench fa-fw"></i> Route Planner </a>
                        </li>
                        <li>
                            <!--<a href="{% url 'calender:dashboardBookingUrl' %}"><i class="fa fa-key fa-fw"></i> Booking Link Generator</a>-->
                            <a href="{% url 'calender:dashboardAppointments' %}"><i class="fa fa-calendar fa-fw"></i> Appointments</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        {% block content %}{% endblock %}

        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->


    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'calender/dashboard-bootstrap/vendor/metisMenu/metisMenu.min.js'%}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'calender/dashboard-bootstrap/dist/js/sb-admin-2.js' %}"></script>

    <script src="{% static 'calender/form-bootstrap/assets/js/retina-1.1.0.min.js' %}"></script>
    <script src="{% static 'calender/form-bootstrap/assets/js/scripts.js' %}"></script>




    </body>

    </html>

calender/templates/calender/dashboard_change_password.html
{% extends 'calender/dashboard_base.html' %}
{% block content %}
<!--{% include 'calender/message.html' %}-->


<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Change Password</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>

    <div class="row">
        {% for message in messages %}
        <div class=" col-lg-12 alert {{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Change Password
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body"/>

                <ul class="list-group">
                    <li class="list-group-item"> Your password can't be too similar to your other personal information.</li>
                    <li class="list-group-item"> Your password must contain at least 8 characters.</li>
                    <li class="list-group-item"> Your password can't be a commonly used password.</li>
                    <li class="list-group-item"> Your password can't be entirely numeric.</li>
                </ul>


                <form class="form-horizontal" method="post">{% csrf_token %}
                    <fieldset>

                        {% for field in form %}
                        {% if field.errors %}
                        <div class="control-group error">
                            <label class="control-label">{{ field.label }}</label>
                            <div class="controls">{{ field }}
                                <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                            </div>
                        </div>
                        {% else %}
                        <div class="control-group">
                            <label class="control-label">{{ field.label }}</label>
                            <div class="controls">{{ field }}
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </fieldset>
                    <br>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary" >Submit</button>
                    </div>
                </form>

            </div>
            <!-- /.panel-body -->

        </div>


    </div>
</div>
<!-- /.container-fluid -->
</div>






{% endblock %}